Feature/tela anotacao
Lontras-e-Preguicas/cnotes-app pull request #10
Opened 2021-03-19 19:42 UTC by AmandaJacomette

### Tela de Anotação

- Completa, mas sem integração

### Tela de comentários

- Quase completa 
- Botão de inserir não funcional, mas a função já esta pronta

2021-03-19 20:13 UTC, DanielHLelis requested changes
Algumas medidas estranhas marcadas, se tiver uma justificativa pra ela, me avise... O modal poderia ter sido feito de um jeito mais genérico, já que já tem código duplicado e ele ainda virá a ser usado em mais telas...

2021-03-19 20:13 UTC, LiviaLelis commented on app/src/components/containers/ConjuntoAnotacoes/ConjuntoAnotacoesContainer.js
> +    //console.warn("Abrindo", id);
```suggestion
```

2021-03-19 20:13 UTC, LiviaLelis commented on app/src/components/containers/Login/LoginContainer.js
> +    //navigation.navigate("HomeTabs");
```suggestion
```

2021-03-19 20:13 UTC, LiviaLelis commented on app/src/components/presentational/Anotacao/AnotacaoPresentational.js
> +  const [edit, setEdit] = useState(true); //ativar ou desativar a edicao
Gerenciar estado no container

2021-03-19 20:13 UTC, DanielHLelis commented on app/src/components/presentational/Anotacao/AnotacaoPresentational.js
> +            //placeholder={"Conteudo..."}
```suggestion
```

2021-03-19 20:13 UTC, DanielHLelis commented on app/src/components/presentational/Anotacao/ModalAvaliacao.js
> +  width: 55%;
Por que 55%?

2021-03-19 20:13 UTC, DanielHLelis commented on app/src/components/presentational/Anotacao/ModalAvaliacao.js
> +  margin-top: 15%;
Por que 15%?

2021-03-19 20:13 UTC, DanielHLelis commented on app/src/components/presentational/Anotacao/styles.js
> +  height: 10%;
Por que 10%?

2021-03-19 20:13 UTC, DanielHLelis commented on app/src/components/presentational/Anotacao/styles.js
> +  height: 20%;
Por que 20%?

2021-03-19 20:13 UTC, DanielHLelis commented on app/src/components/presentational/Comentarios/ComentariosPresentational.js
> +import React, { useRef, useState } from "react";
Vários imports não utilizados

2021-03-19 20:13 UTC, DanielHLelis commented on app/src/components/presentational/Comentarios/Modal.js
> +  margin-top: 15%;
Por que 15%?

2021-03-19 20:13 UTC, DanielHLelis commented on app/src/components/presentational/Comentarios/Modal.js
> +  height:35%;
Por que 35%?

2021-03-19 20:13 UTC, DanielHLelis commented on app/src/components/presentational/Comentarios/Modal.js
> +  width: 55%;
Por que 55%

2021-03-19 20:13 UTC, DanielHLelis commented on app/src/components/presentational/Comentarios/styles.js
> +  border-color: ${"#9975E4"};
```suggestion
  border-color: #9975E4;
```

2021-03-19 20:15 UTC, DanielHLelis commented
Outro comentário: tem vários conflitos relacionados àquelas pequenas correções? Vocês deram pull na dev antes de abrir o PR? Ou deram um rebase (não recomendo)?

2021-03-21 14:42 UTC, AmandaJacomette commented on app/src/components/presentational/Anotacao/ModalAvaliacao.js
> +  margin-top: 15%;
Era pra não tampar o header, mas mudei pro getSpacing agora

2021-03-21 14:43 UTC, AmandaJacomette commented on app/src/components/presentational/Anotacao/styles.js
> +  height: 10%;
Retirei

2021-03-21 14:43 UTC, AmandaJacomette commented on app/src/components/presentational/Anotacao/styles.js
> +  height: 20%;
Retirei

2021-03-21 14:44 UTC, AmandaJacomette commented on app/src/components/presentational/Comentarios/ComentariosPresentational.js
> +import React, { useRef, useState } from "react";
Acho que tirei todos agora

2021-03-21 14:45 UTC, AmandaJacomette commented on app/src/components/containers/ConjuntoAnotacoes/ConjuntoAnotacoesContainer.js
> +    //console.warn("Abrindo", id);
Retirado

2021-03-21 14:48 UTC, AmandaJacomette commented on app/src/components/presentational/Comentarios/Modal.js
> +  margin-top: 15%;
Era pra não tampar o header

2021-03-21 14:53 UTC, AmandaJacomette commented on app/src/components/presentational/Comentarios/Modal.js
> +  height:35%;
Sem isso o tamanho do modal fica todo errado (ainda não sei o porque)

2021-03-21 14:54 UTC, AmandaJacomette commented on app/src/components/presentational/Comentarios/Modal.js
> +  width: 55%;
Pro tamanho dos botões ficarem certos

2021-03-21 14:55 UTC, AmandaJacomette commented on app/src/components/presentational/Comentarios/styles.js
> +  border-color: ${"#9975E4"};
Concertado

2021-03-21 16:54 UTC, isacruzdora commented on app/src/components/presentational/Anotacao/ModalAvaliacao.js
> +  width: 55%;
Resolvido

2021-03-21 16:54 UTC, isacruzdora commented on app/src/components/presentational/Comentarios/Modal.js
> +  width: 55%;
Resolvido

2021-03-23 02:03 UTC, merged