Tela atividades recentes
Lontras-e-Preguicas/cnotes-app pull request #8
Opened 2021-03-13 18:13 UTC by isacruzdora

Tela Atividades - com Modal para excluir notificações (sem integração)

2021-03-13 18:26 UTC, DanielHLelis requested changes
Alguns pequenos erros quase irrelevantes, outros um pouco mais impactantes (aka Header). No geral, muito bom!

2021-03-13 18:26 UTC, DanielHLelis commented on app/src/components/presentational/Atividades/AtividadesPresentational.js
> +];
Passar os dados através do container

2021-03-13 18:26 UTC, DanielHLelis commented on app/src/components/presentational/Atividades/AtividadesPresentational.js
> +            keyExtractor={(item, index) => item + index}
item é um objeto, por mais que não faça muita diferença, ficaria melhor:

```suggestion
            keyExtractor={(item, index) => index.toString()}
```
ou
```suggestion
            keyExtractor={(item, index) => item.id}
```

2021-03-13 18:26 UTC, DanielHLelis commented on app/src/components/presentational/Atividades/Modal.js
> +  elevation: 10;
Também adicionar propriedades de sombra do iOS [ref](https://reactnative.dev/docs/shadow-props).

(Tem um exemplo no FAB da tela de caderno, se não me engano)

2021-03-13 18:26 UTC, DanielHLelis commented on app/src/components/presentational/Atividades/Modal.js
> +  margin-top: 15%;
margem percentual diferente de `50%` geralmente não é um bom sinal... Era necessário?

2021-03-13 18:26 UTC, DanielHLelis commented on app/src/components/presentational/Atividades/styles.js
> +`;
Usar o _core component_ de Header...

2021-03-13 18:26 UTC, DanielHLelis commented on app/src/components/presentational/Atividades/styles.js
> +  padding: 20px;
```suggestion
  padding: ${Spacing.getSpacing(20)};
```

2021-03-13 18:26 UTC, DanielHLelis commented on app/src/components/presentational/Atividades/styles.js
> +  width: 20%;
Por que 20%?

2021-03-13 18:26 UTC, DanielHLelis commented on app/src/routes.js
> -      <MainStack.Screen name="AuthStack" component={AuthRoutes} />
Ehhhh, acho que não era pra isso ter sido deletado...

2021-03-13 18:26 UTC, DanielHLelis commented on app/src/routes.js
> +      <MainStack.Screen name="Activity" component={AtividadesScreen} />
A tela de atividades já não estava no `HomeTabs`?

2021-03-13 18:26 UTC, DanielHLelis commented on app/src/screens/Atividades.js
> +    <StatusBar style="light" />
```suggestion
    <StatusBar style="dark" />
```

2021-03-29 23:44 UTC, isacruzdora commented on app/src/components/presentational/Atividades/AtividadesPresentational.js
> +];
Resolvido

2021-03-29 23:44 UTC, isacruzdora commented on app/src/components/presentational/Atividades/AtividadesPresentational.js
> +            keyExtractor={(item, index) => item + index}
Resolvido

2021-03-29 23:45 UTC, isacruzdora commented on app/src/components/presentational/Atividades/Modal.js
> +  margin-top: 15%;
Resolvido

2021-03-29 23:45 UTC, isacruzdora commented on app/src/components/presentational/Atividades/styles.js
> +`;
Resolvido

2021-03-29 23:46 UTC, isacruzdora commented on app/src/components/presentational/Atividades/styles.js
> +  width: 20%;
Pra ficar alinhado de forma correta

2021-03-29 23:46 UTC, isacruzdora commented on app/src/routes.js
> -      <MainStack.Screen name="AuthStack" component={AuthRoutes} />
Concertado

2021-03-29 23:56 UTC, isacruzdora commented on app/src/screens/Atividades.js
> +    <StatusBar style="light" />
Resolvido

2021-03-29 23:56 UTC, isacruzdora commented on app/src/routes.js
> +      <MainStack.Screen name="Activity" component={AtividadesScreen} />
Resolvido

2021-03-30 22:00 UTC, merged